### ISSUE TITLE
grad of STE

### ISSUE THREAD

**Issue by tzm1003306213** [PannenetsF/TQT#4]
I think grad_input = 1 is wrong. For STE, d output / d input = 1. So, grad_input = grad_output.

**Comment by PannenetsF** [comment]
Yes, this repo may get lots of this bugs, for it is my first re-implement of quantization paper. 

For now, I re-implement tqt in MQBench, https://github.com/ModelTC/MQBench/blob/main/mqbench/fake_quantize/tqt.py. 

This TQT is well tested over yolo-x network and run on FPGA, so just use mqbench instead of this tqt.

Thanks for your issue!
